# Generated by Django 4.2.4 on 2024-03-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
