# Generated by Django 4.2.4 on 2024-03-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_employees_products_users_name_users_pfp_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Clients',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.clients')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.categories')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.products')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.categories'),
        ),
    ]
